<link href="css/tab1style.css" rel="stylesheet">
```{recho=FALSE}
### Mail

TXTRAWFILE='~/Documents/submission.txt'
filter.time=data.frame(from=as.Date('2014-05-29','%Y-%m-%d'),to=as.Date('2014-06-03','%Y-%m-%d'))

fetchinfo<-function(re){
  
  return (list(
    GivenName =  strsplit(re[2],split='Name')[[1]][2],
    FistName  =  strsplit(re[4],split='Name')[[1]][2],
    StdID     =  strsplit(re[5],split='# ')[[1]][2],
    Email     =  strsplit(re[6],split='Address ')[[1]][2],
    Course    =  strsplit(re[8],split='S 150) ')[[1]][2],
    Date      =  format.Date(as.Date(strsplit(re[9],split='exam ')[[1]][2],"%d/%m/%Y"),"%Y-%m-%d"),
    Time      =  gsub('[^[:digit:]:ampm]','',strsplit(re[10],split=' exam ')[[1]][2])
  ));
}
con=file(TXTRAWFILE)
open(con)
re1=NULL
N=1000
for (i in 1:N){
  readLines(con,n=10)->re
  if (length(re)==0) break;
  rbind(re1,do.call(cbind,fetchinfo(re))) -> re1
  
}
unlink(con)

#keyword filtering
keyword="291"
re1=re1[ grep(keyword,re1[,5]),]

unique(re1[sort(re1[,6], index.return = TRUE)$ix,]) -> report
```

The time schedule is:

```{r,results='asis', echo=FALSE}
knitr::kable(filter.time)
```

The name list for STA 291 EXAM 1 is as follows:

```{r,results='asis', echo=FALSE}
knitr::kable(report)
```

The numbers of students are grouped by date:

```{r,results='asis', echo=FALSE}
report.df<-as.data.frame(report)
library(psych)
psych::describeBy(report.df,report.df$Date)->rr
fff<-function(x){
l=length(x)
re=rep(0,l)
for (i in 1:l) re[i]=x[[i]][1,2] 
re
}
knitr::kable(data.frame(Date=names(rr),Numbers=fff(rr),Proctor="TBD"))
```

<FONT COLOR="#FF0000"><Strong>Warning</Strong>: these students registered unavaliable date:

```{r,results='asis', echo=FALSE}
date.tmp = as.Date(report[,6],'%Y-%m-%d')
knitr::kable(report.df[!(date.tmp >= filter.time$from) | !(date.tmp <= filter.time$to),])
```

</FONT>

Please Contact them if needed.
